### PR TITLE
Fix JSON incoherence in NekoClient

### PR DESCRIPTION
**Pull request by ghost**
As of right now entering an invalid URL in https://api.nekos.dev/api/v3/images/ returns a JSON message with a list of possible entries that the client should be using, and a status code of 404 inside of the JSON.

However, this causes `HttpResponseMessage.EnsureSuccessStatusCode()` used in `line 66` of `NekosClient.cs` to not throw an exception since the server technically sent back something with a *HTTP* 200 code, even though the returned *JSON* states that this is a 404 resource not found error. 

This, in turn, causes `NekoClient.SendRequest()` to return a Request instance that apparently indicates success... except that the request's ImageUrl property is null, when it shouldn't even return a successful Request instance at all.

The fix I just did is to simply check the property `status.code` (which always seems to be returned in any request that doesn't bring up a 404 HTTP error) present in the JSON returned by the server and to throw an exception when the code is not 200.

[I worked on this message for 72 hours pls accept the PR lmao]

### CODE REVIEW

**Comment by xXBuilderBXx** [comment]
I will check this in a bit thanks for helping.

**Comment by reNemesic** [comment]
Please take your time, it's not like the change I did actually compiles (i mean that i don't know if it does), i literally just did it in the github text editor

**Comment by reNemesic** [comment]
"Will check this in a bit"
5 days ago

**Comment by xXBuilderBXx** [comment]
I've been way too busy irl but will check it today my bad.

**Pull request closed without merging**
